### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by steef84** [CutePoisonX/PoisonConvert#10]
Trying to convert with poisonconvert --start --config-file AppleTV3. Got error on my DS213+

Any pointers for me? It looks like it tries to remux fanart also. In folders with only MKV it remuxes properly!

-----------------------------------------------------
-----------------------------------------------------
PoisonConvert Logfile for Job: /volume1/video/films/22 Jump Street (2014)/22.Jump.Street.2014.1080p.Bluray.x264.nfo
-----------------------------------------------------
Started Processing

1. Analyzed File

   Video:     Container       nfo
              Codec           ansi
              Bitrate         46000
              Resolution      640x400
              Fps             25

2. ffmpeg command line

   /volume1/@appstore/VideoStation/bin/ffmpeg -i /volume1/video/films/22 Jump Street (2014)/22.Jump.Street.2014.1080p.Bluray.x264.nfo.old -map 0:0 -c:v:0 h264 -strict $

3. ffmpeg output
-----------------------------------------------------ffmpeg version 2.0.2 Copyright (c) 2000-2013 the FFmpeg developers
  built on Jun  9 2015 13:17:35 with gcc 4.3.2 (GCC)
  configuration: --prefix=/usr/pkg --incdir='${prefix}/include/ffmpeg' --arch=powerpc --target-os=linux --cross-prefix=/usr/local/powerpc-none-linux-gnuspe/bin/powerpc$
  libavutil      52. 38.100 / 52. 38.100
  libavcodec     55. 18.102 / 55. 18.102
  libavformat    55. 12.100 / 55. 12.100
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 79.101 /  3. 79.101
  libswscale      2.  3.100 /  2.  3.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  3.100 / 52.  3.100
/volume1/video/films/22 Jump Street (2014)/22.Jump.Street.2014.1080p.Bluray.x264.nfo.old: Invalid data found when processing input

C O N V E R S I O N    F A I L E D

-----------------------------------------------------
PoisonCovert_Settings
-----------------------------------------------------

-----Settings-----
config-file EmptyConfig
config-path /usr/syno/etc/poisonconvert/PoisonConvert_Config-files/
ffmpeg-cmd /volume1/@appstore/VideoStation/bin/ffmpeg
ffprobe-cmd /volume1/@appstore/VideoStation/bin/ffprobe
qt-faststart-cmd /usr/syno/bin/qt-faststart
delete No
optimize No
log-path /volume1/PoisonConvert_v1.4.1/
movies-path /volume1/video/films/
destination Destination equals source
-----Settings-----

**Comment by CutePoisonX** [comment]
Thanks for reporting this! I try to take a look at this on the weekend

**Comment by CutePoisonX** [comment]
Hi! Can you post the contents of the nfo file here?

**Comment by steef84** [comment]
complete content of that specific folder is seen here .... (zipped version)
https://www.dropbox.com/s/wi9maqs7h8bo0ib/22%20Jump%20Street%20%282014%29.zip?dl=0

**Comment by steef84** [comment]
Any progress on this one?

**Comment by CutePoisonX** [comment]
Hey. I can reproduce the bug but will need some time to fix it.
You can expect a fix the next week (most likely on weekend).

**Comment by CutePoisonX** [comment]
Sorry, will need a few more days to fix it - but I'm on it

**Comment by CutePoisonX** [comment]
I just released PoisonConvert v1.4.2 which solves this issue. It includes a setting, where you can exclude certain fileextensions, so PoisonConvert will no longer try to process metadata.
