### ISSUE TITLE
Compilation errors 

### ISSUE THREAD

**Issue by Foncekar** [CutePoisonX/PoisonConvert#4]
I have a problem when i tried compilation on my DS214play.
Any idea ?
(Sorry for my english i'm french )

DiskStation> make
g++ -c -Wall -g -o UserInterface.o UserInterface.cpp -MMD -MF ./UserInterface.o.d
g++ -c -Wall -g -o VectorManager.o VectorManager.cpp -MMD -MF ./VectorManager.o.d
VectorManager.cpp: In member function 'std::string VectorManager::sendSinglePreference(unsigned int, unsigned int, unsigned int)':
VectorManager.cpp:69: warning: control reaches end of non-void function
g++ -c -Wall -g -o FileReadException.o FileReadException.cpp -MMD -MF ./FileReadException.o.d
g++ -c -Wall -g -o YesNoSetting.o YesNoSetting.cpp -MMD -MF ./YesNoSetting.o.d
g++ -c -Wall -g -o StartMode.o StartMode.cpp -MMD -MF ./StartMode.o.d
StartMode.h: In constructor 'StartMode::StartMode(UserInterface&, VectorSourceManager&, FileManager&, AnalyzeMedia&, SettingsMode&)':
StartMode.h:53: warning: 'StartMode::analyze_' will be initialized after
StartMode.h:51: warning:   'SettingsMode& StartMode::settings_'
StartMode.cpp:31: warning:   when initialized here
StartMode.h: In copy constructor 'StartMode::StartMode(const StartMode&)':
StartMode.h:62: warning: 'StartMode::nr_sub_targets_' will be initialized after
StartMode.h:51: warning:   'SettingsMode& StartMode::settings_'
StartMode.cpp:37: warning:   when initialized here
StartMode.cpp: In member function 'void StartMode::WriteLogFfmpeg(std::string)':
StartMode.cpp:816: warning: comparison between signed and unsigned integer expressions
StartMode.cpp: In member function 'int StartMode::applySettings()':
StartMode.cpp:430: warning: control reaches end of non-void function
StartMode.cpp: In member function 'int StartMode::gettingInfos(const std::string&, std::string&)':
StartMode.cpp:344: warning: control reaches end of non-void function
StartMode.cpp: In member function 'virtual int StartMode::executeCommand()':
StartMode.cpp:328: warning: control reaches end of non-void function
StartMode.cpp: In member function 'int StartMode::gettingFiles()':
StartMode.cpp:150: warning: control reaches end of non-void function
g++ -c -Wall -g -o Settings.o Settings.cpp -MMD -MF ./Settings.o.d
g++ -c -Wall -g -o StreamPreference.o StreamPreference.cpp -MMD -MF ./StreamPreference.o.d
StreamPreference.cpp: In member function 'int StreamPreference::saveTarget(unsigned int)':
StreamPreference.cpp:43: warning: control reaches end of non-void function
g++ -c -Wall -g -o SettingsMode.o SettingsMode.cpp -MMD -MF ./SettingsMode.o.d
SettingsMode.cpp: In member function 'void SettingsMode::AlignSpaces(unsigned int, unsigned int)':
SettingsMode.cpp:145: warning: comparison between signed and unsigned integer expressions
SettingsMode.cpp: In member function 'int SettingsMode::listSettings()':
SettingsMode.cpp:108: warning: control reaches end of non-void function
SettingsMode.cpp: In member function 'virtual int SettingsMode::executeCommand()':
SettingsMode.cpp:97: warning: control reaches end of non-void function
g++ -c -Wall -g -o FileWriteException.o FileWriteException.cpp -MMD -MF ./FileWriteException.o.d
g++ -c -Wall -g -o FileException.o FileException.cpp -MMD -MF ./FileException.o.d
g++ -c -Wall -g -o OpenFileException.o OpenFileException.cpp -MMD -MF ./OpenFileException.o.d
g++ -c -Wall -g -o VectorSourceManager.o VectorSourceManager.cpp -MMD -MF ./VectorSourceManager.o.d
VectorSourceManager.cpp: In member function 'int VectorSourceManager::editTarget(unsigned int, unsigned int, unsigned int, unsigned int)':
VectorSourceManager.cpp:146: warning: control reaches end of non-void function
VectorSourceManager.cpp: In member function 'int VectorSourceManager::linkNewTarget(unsigned int, unsigned int, unsigned int)':
VectorSourceManager.cpp:126: warning: control reaches end of non-void function
VectorSourceManager.cpp: In member function 'int VectorSourceManager::moveElement(unsigned int, unsigned int, unsigned int)':
VectorSourceManager.cpp:117: warning: control reaches end of non-void function
VectorSourceManager.cpp: In member function 'int VectorSourceManager::editPreference(unsigned int, unsigned int, unsigned int, std::string&)':
VectorSourceManager.cpp:98: warning: control reaches end of non-void function
VectorSourceManager.cpp: In member function 'int VectorSourceManager::deleteFromVector(unsigned int, unsigned int)':
VectorSourceManager.cpp:74: warning: control reaches end of non-void function
VectorSourceManager.cpp: In member function 'virtual std::vector<StreamPreference*, std::allocator<StreamPreference*> >& VectorSourceManager::getVector(unsigned int)':
VectorSourceManager.cpp:63: warning: control reaches end of non-void function
VectorSourceManager.cpp: In member function 'virtual int VectorSourceManager::saveToVector(std::string&, std::string&, std::string&, std::string&, std::string&, unsigned int, unsigned int)':
VectorSourceManager.cpp:44: warning: control reaches end of non-void function
g++ -c -Wall -g -o ConfigMode.o ConfigMode.cpp -MMD -MF ./ConfigMode.o.d
ConfigMode.cpp: In member function 'unsigned int ConfigMode::specifyTarget(const std::string&, const std::string&, const std::string&, const std::string&, const std::string&)':
ConfigMode.cpp:600: warning: comparison between signed and unsigned integer expressions
ConfigMode.cpp: In member function 'int ConfigMode::deleteTarget()':
ConfigMode.cpp:2055: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::deleteRule()':
ConfigMode.cpp:1915: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::deleteConfig()':
ConfigMode.cpp:1789: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::listTarget(std::string&, std::string&, std::string&, std::string&, std::string&)':
ConfigMode.cpp:1714: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::listRule(std::string&, std::string&, std::string&, std::string&, std::string&)':
ConfigMode.cpp:1637: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::list()':
ConfigMode.cpp:1550: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::createOutputAudio()':
ConfigMode.cpp:1189: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::createOutputVideo()':
ConfigMode.cpp:1117: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'unsigned int ConfigMode::setPriority()':
ConfigMode.cpp:570: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::createRuleSub()':
ConfigMode.cpp:537: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::createRuleAudio()':
ConfigMode.cpp:498: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::createRuleVideo()':
ConfigMode.cpp:405: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::createRule()':
ConfigMode.cpp:283: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'int ConfigMode::newConfig()':
ConfigMode.cpp:155: warning: control reaches end of non-void function
ConfigMode.cpp: In member function 'virtual int ConfigMode::executeCommand()':
ConfigMode.cpp:96: warning: control reaches end of non-void function
g++ -c -Wall -g -o FileManager.o FileManager.cpp -MMD -MF ./FileManager.o.d
FileManager.cpp: In member function 'int FileManager::readSettings()':
FileManager.cpp:100: warning: control reaches end of non-void function
g++ -c -Wall -g -o main.o main.cpp -MMD -MF ./main.o.d
main.cpp: In function 'int main(int, char**)':
main.cpp:135: warning: comparison between signed and unsigned integer expressions
main.cpp:265: warning: comparison between signed and unsigned integer expressions
main.cpp:309: warning: comparison between signed and unsigned integer expressions
g++ -c -Wall -g -o AnalyzeMedia.o AnalyzeMedia.cpp -MMD -MF ./AnalyzeMedia.o.d
AnalyzeMedia.cpp: In member function 'virtual std::vector<StreamPreference*, std::allocator<StreamPreference*> >& AnalyzeMedia::getVector(unsigned int)':
AnalyzeMedia.cpp:58: warning: control reaches end of non-void function
AnalyzeMedia.cpp: In member function 'virtual int AnalyzeMedia::saveToVector(std::string&, std::string&, std::string&, std::string&, std::string&, unsigned int, unsigned int)':
AnalyzeMedia.cpp:45: warning: control reaches end of non-void function
g++ -c -Wall -g -o FolderSetting.o FolderSetting.cpp -MMD -MF ./FolderSetting.o.d
g++ -c -Wall -g -o Mode.o Mode.cpp -MMD -MF ./Mode.o.d
g++  -o poisonconvert UserInterface.o VectorManager.o FileReadException.o YesNoSetting.o StartMode.o Settings.o StreamPreference.o SettingsMode.o FileWriteException.o FileException.o OpenFileException.o VectorSourceManager.o ConfigMode.o FileManager.o main.o AnalyzeMedia.o FolderSetting.o Mode.o
DiskStation> make install
install --mode=755 poisonconvert /opt/bin/
cp -r PoisonConvert_Config-files/ /opt/etc/PoisonConvert_Config-files/
DiskStation> poisonconvert
Segmentation fault (core dumped)

**Comment by TimDowker** [comment]
I just ran head first into this same problem.  Any word on a fix?  Or possible work around?

Thanks

**Comment by CutePoisonX** [comment]
Hi! Do you also have a model with Intel atom processor? I will address this issue in late February when I have more time. The only problem is that I don't have an Intel based DiskStation, so I would need somebody to test it. Are you interested?

**Comment by ajass** [comment]
I have a 713+ installing this right now with the default settings.  Excellent work.  I can help you test.

**Comment by CutePoisonX** [comment]
Awesome! Thanks, I will contact you later this month.

**Comment by MortenMou** [comment]
I have this same problem on my DS214play. Dont mind helping if you need even though my programming skills are close to none in this situation. ;)

**Comment by TimDowker** [comment]
Sorry for the delay in my response - just finished setting up my new DS1815+.  I can help out as well but I now have the Avoton processor so I don't know if that's gonna fit in with your testing protocols.

**Comment by CutePoisonX** [comment]
Hi!
Sorry for the late response, life is busy right now. I've already planned to address this issue in February but time did not permit. 
I promise I will take care of it but not until the end of March when I've got more time left. I then will contact you for testing purposes, if this is ok.
Sorry again and thanks for your patience!

**Comment by CutePoisonX** [comment]
Sorry again for the late response. Finally I've got time to address this issue. Still anybody with the same problem who would like to solve this issue with me?

**Comment by CutePoisonX** [comment]
I think I try to cross compile the tool for the Intel based DiskStations... cross your fingers, I have never done this before

**Comment by CutePoisonX** [comment]
Hi TimDowker, I've compiled it on another machine for the DS1815+, would you like to try it? I just don't know yet how to attach the binary here ...

**Comment by TimDowker** [comment]
Sure!  I sent you an email.

**Comment by CutePoisonX** [comment]
Hey all, since the binary i sent to TimDowker was executable I will provide compiled binaries for all DS models so that you won't have to compile it by yourself. 
The binaries will be appended to a new release of PoisonConvert on github. Nevertheless, I keep this issue open until all binaries are ready.

**Comment by CutePoisonX** [comment]
Hi! I've finally released v1.4.1 with pre-compiled binaries of PoisonConvert. Please use the install script at: http://www.mediaware-factory.com/#!leer/c1y0n to install poisonconvert (it will select the right version based on your DiskStation). Hope it works for all of you!
