### ISSUE TITLE
How to use Task Scheduler ?

### ISSUE THREAD

**Issue by moodyblue** [CutePoisonX/PoisonConvert#6]
I am trying to use the Task Scheduler in DSM 5.2 to run poisonconvert, but so far without success. Would it be possible to post a working example of a script ?

Thanks

**Comment by CutePoisonX** [comment]
Hi, I've attached a screenshot how you set the scheduler (it's in german but that should not be a problem).
You can try to execute it manually in the scheduler and then check the logfiles of poisonconvert or open a terminal, ssh to your diskstation (admin user) and write: /tmp/synoschedtask --get
There you can check the status of the task (should display SUCCESS).

Does this work? If not, what is the status of the task?

![bildschirmfoto 2015-05-25 um 11 52 06](https://cloud.githubusercontent.com/assets/4478926/7795363/9267e12a-02d4-11e5-9142-1581ddfaac90.png)

**Comment by moodyblue** [comment]
Thanks, but didn't work for me. I had to create the following script:

#!/bin/sh
PATH=/opt/bin
/opt/bin/poisonconvert start
exit

And then, in Task Scheduler, I put:

/root/ConvertMP4.sh

2015-05-25 10:56 GMT+01:00 CutePoisonX <notifications@github.com>:

**Comment by CutePoisonX** [comment]
Ok, seems like /opt/bin was not included in your PATH variable. For v1.4.1, the default destination for PoisonConvert will be usr/bin I think.
