### ISSUE TITLE
2 Problems unterminated quoted string

### ISSUE THREAD

**Issue by TimDowker** [CutePoisonX/PoisonConvert#8]
**Problem #1**
I receive the following error while trying to convert a TV Show

*poisonconvert --start --config-file Chromecast*
*Processing config-file: Chromecast*
*Found file: /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv*

*Started job 1/1: The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv*
*Converting...*
*Finished converting...*
*Started optimizing...*
**sh: syntax error: unterminated quoted string**
*Finished optimizing...*
*Finished job /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv*
*Done - all items succeeded! :)*

**Problem #2**
After a supposed "successful" processing - the new file gets deleted.  I ran the conversion twice both with the same results!

Log File:

-----------------------------------------------------
-----------------------------------------------------
PoisonConvert Logfile for Job: /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv
-----------------------------------------------------
Started Processing

1. Analyzed File

   Video:     Container       mkv
              Codec           h264
              Bitrate         7948000
              Resolution      1920x1076
              Fps             29.97

   Audio:     Codec           ac3
              Channels        6
              Language        =1
              Bitrate         384000
              Sample Rate     48000

2. ffmpeg command line

   /usr/bin/ffmpeg -i /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv.old -map 0:0 -map 0:1 -c:v:0 copy -c:a:0 aac -strict -2 -y /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mp4

3. ffmpeg output
-----------------------------------------------------ffmpeg version 2.1.1 Copyright (c) 2000-2013 the FFmpeg developers
  built on Dec 29 2014 05:43:07 with gcc 4.7.3 (crosstool-NG 1.18.0) 20130102 (prerelease)
  configuration: --disable-yasm --enable-gpl --enable-libx264 --enable-libmp3lame --enable-nonfree --enable-cross-compile --arch=avoton --target-os=linux --cross-prefix=/media/data/spksrc_20141228/toolchains/syno-avoton-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/usr/local/ffmpeg --extra-cflags=-I/media/data/spksrc_20141228/spk/ffmpeg/work-avoton-5.1/install/usr/local/ffmpeg/include --extra-ldflags=-L/media/data/spksrc_20141228/spk/ffmpeg/work-avoton-5.1/install/usr/local/ffmpeg/lib --extra-libs=-ldl
  libavutil      52. 48.101 / 52. 48.101
  libavcodec     55. 39.101 / 55. 39.101
  libavformat    55. 19.104 / 55. 19.104
  libavdevice    55.  5.100 / 55.  5.100
  libavfilter     3. 90.100 /  3. 90.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100
Input #0, matroska,webm, from '/volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv.old':
  Metadata:
    creation_time   : 2015-07-23 05:23:21
  Duration: 00:43:15.33, start: 0.000000, bitrate: 7948 kb/s
    Stream #0:0: Video: h264 (High), yuv420p, 1920x1076, SAR 1:1 DAR 480:269, 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
    Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
Output #0, mp4, to '/volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mp4':
  Metadata:
    encoder         : Lavf55.19.104
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1076 [SAR 1:1 DAR 480:269], q=2-31, 29.97 fps, 16k tbn, 1k tbc (default)
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, 5.1(side), fltp, 128 kb/s (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (ac3 -> aac)
Press [q] to stop, [?] for help
frame=  106 fps=0.0 q=-1.0 size=    5407kB time=00:00:03.73 bitrate=11864.1kbits/s    
frame=  224 fps=223 q=-1.0 size=    9640kB time=00:00:07.50 bitrate=10516.9kbits/s    
frame=  342 fps=227 q=-1.0 size=   13474kB time=00:00:11.41 bitrate=9671.1kbits/s    
...
frame=77052 fps=227 q=-1.0 size= 2414819kB time=00:42:51.09 bitrate=7694.1kbits/s    
frame=77172 fps=227 q=-1.0 size= 2419583kB time=00:42:54.95 bitrate=7697.7kbits/s    
frame=77289 fps=227 q=-1.0 size= 2423313kB time=00:42:58.90 bitrate=7697.8kbits/s    
frame=77401 fps=227 q=-1.0 size= 2427488kB time=00:43:02.76 bitrate=7699.5kbits/s    
frame=77519 fps=227 q=-1.0 size= 2431201kB time=00:43:06.53 bitrate=7700.0kbits/s    
frame=77628 fps=227 q=-1.0 size= 2433861kB time=00:43:10.35 bitrate=7697.1kbits/s    
frame=77750 fps=227 q=-1.0 size= 2436358kB time=00:43:14.38 bitrate=7693.0kbits/s    
frame=77782 fps=227 q=-1.0 Lsize= 2439809kB time=00:43:15.30 bitrate=7701.2kbits/s    

video:2395933kB audio:40640kB subtitle:0 global headers:0kB muxing overhead 0.132844%

4. Analyzed processed file

   Video:     Container       mp4
              Codec           h264
              Bitrate         7701000
              Resolution      1920x1076
              Fps             29.97

   Audio:     Codec           aac
              Channels        6
              Language        und
              Bitrate         128278
              Sample Rate     48000

C O N V E R S I O N    S U C C E E D E D
-----------------------------------------------------

4. qt-faststart output

-----------------------------------------------------
-----------------------------------------------------
PoisonConvert Logfile for Job: /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv
-----------------------------------------------------
Started Processing

1. Analyzed File

   Video:     Container       mkv
              Codec           h264
              Bitrate         7948000
              Resolution      1920x1076
              Fps             29.97

   Audio:     Codec           ac3
              Channels        6
              Language        =1
              Bitrate         384000
              Sample Rate     48000

2. ffmpeg command line

   /usr/bin/ffmpeg -i /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv.old -map 0:0 -map 0:1 -c:v:0 copy -c:a:0 aac -strict -2 -y /volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mp4

3. ffmpeg output
-----------------------------------------------------ffmpeg version 2.1.1 Copyright (c) 2000-2013 the FFmpeg developers
  built on Dec 29 2014 05:43:07 with gcc 4.7.3 (crosstool-NG 1.18.0) 20130102 (prerelease)
  configuration: --disable-yasm --enable-gpl --enable-libx264 --enable-libmp3lame --enable-nonfree --enable-cross-compile --arch=avoton --target-os=linux --cross-prefix=/media/data/spksrc_20141228/toolchains/syno-avoton-5.1/work/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu- --prefix=/usr/local/ffmpeg --extra-cflags=-I/media/data/spksrc_20141228/spk/ffmpeg/work-avoton-5.1/install/usr/local/ffmpeg/include --extra-ldflags=-L/media/data/spksrc_20141228/spk/ffmpeg/work-avoton-5.1/install/usr/local/ffmpeg/lib --extra-libs=-ldl
  libavutil      52. 48.101 / 52. 48.101
  libavcodec     55. 39.101 / 55. 39.101
  libavformat    55. 19.104 / 55. 19.104
  libavdevice    55.  5.100 / 55.  5.100
  libavfilter     3. 90.100 /  3. 90.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100
Input #0, matroska,webm, from '/volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mkv.old':
  Metadata:
    creation_time   : 2015-07-23 05:23:21
  Duration: 00:43:15.33, start: 0.000000, bitrate: 7948 kb/s
    Stream #0:0: Video: h264 (High), yuv420p, 1920x1076, SAR 1:1 DAR 480:269, 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
    Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
Output #0, mp4, to '/volume1/temp/The.Amazing.Race.Canada.S03E03.1080p.HDTV-crooks.mp4':
  Metadata:
    encoder         : Lavf55.19.104
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1076 [SAR 1:1 DAR 480:269], q=2-31, 29.97 fps, 16k tbn, 1k tbc (default)
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, 5.1(side), fltp, 128 kb/s (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (ac3 -> aac)
Press [q] to stop, [?] for help
frame=  106 fps=0.0 q=-1.0 size=    5407kB time=00:00:03.54 bitrate=12507.3kbits/s    
frame=  213 fps=212 q=-1.0 size=    9326kB time=00:00:07.33 bitrate=10410.8kbits/s    
frame=  331 fps=220 q=-1.0 size=   13002kB time=00:00:11.24 bitrate=9473.9kbits/s    
frame=  448 fps=223 q=-1.0 size=   18638kB time=00:00:15.01 bitrate=10166.0kbits/s    
frame=  562 fps=224 q=-1.0 size=   23632kB time=00:00:18.79 bitrate=10300.3kbits/s    
frame=  673 fps=223 q=-1.0 size=   29632kB time=00:00:22.50 bitrate=10785.4kbits/s    
...
frame=76948 fps=209 q=-1.0 size= 2410340kB time=00:42:47.70 bitrate=7690.0kbits/s    
frame=77023 fps=208 q=-1.0 size= 2413634kB time=00:42:50.19 bitrate=7693.0kbits/s    
frame=77120 fps=208 q=-1.0 size= 2417303kB time=00:42:53.29 bitrate=7695.4kbits/s    
frame=77221 fps=208 q=-1.0 size= 2421171kB time=00:42:56.72 bitrate=7697.5kbits/s    
frame=77325 fps=208 q=-1.0 size= 2425011kB time=00:43:00.26 bitrate=7699.1kbits/s    
frame=77418 fps=208 q=-1.0 size= 2427869kB time=00:43:03.33 bitrate=7699.0kbits/s    
frame=77523 fps=208 q=-1.0 size= 2431340kB time=00:43:06.83 bitrate=7699.6kbits/s    
frame=77628 fps=208 q=-1.0 size= 2433861kB time=00:43:10.37 bitrate=7697.0kbits/s    
frame=77745 fps=208 q=-1.0 size= 2436299kB time=00:43:14.26 bitrate=7693.2kbits/s    
frame=77782 fps=208 q=-1.0 Lsize= 2439809kB time=00:43:15.30 bitrate=7701.2kbits/s    

video:2395933kB audio:40640kB subtitle:0 global headers:0kB muxing overhead 0.132844%

4. Analyzed processed file

   Video:     Container       mp4
              Codec           h264
              Bitrate         7701000
              Resolution      1920x1076
              Fps             29.97

   Audio:     Codec           aac
              Channels        6
              Language        und
              Bitrate         128278
              Sample Rate     48000

C O N V E R S I O N    S U C C E E D E D
-----------------------------------------------------

4. qt-faststart output

**Comment by CutePoisonX** [comment]
Hello,
do the errors still occur when you switch optimization off?

**Comment by TimDowker** [comment]
Which one?  The delete after process error or the unterminated quoted string error?

**Comment by CutePoisonX** [comment]
Both of them (looks like they are both related to the optimize-function).

**Comment by TimDowker** [comment]
:+1:  Good call - neither error occurs when optimization is turned off.

**Comment by CutePoisonX** [comment]
Ok, I'm on it, thanks for your report!

**Comment by TimDowker** [comment]
No Problem - if you need someone to test - I'm here.

**Comment by CutePoisonX** [comment]
Hi, should be resolved now. Please execute the install script again, or select your binary from: https://github.com/CutePoisonX/PoisonConvert/releases and replace the previous poisonconvert binary with the new one.
