### ISSUE TITLE
Debian Support

### ISSUE THREAD

**Issue by eack** [CutePoisonX/PoisonConvert#9]
Can you support debian, or tell how it will work on a debian based system?
I created the folder `/usr/syno/bin` and `/usr/syno/etc` but it still prints the error:

    There occured an error at reading out the "Settings"-file (some settings were corrupt). Please check settings-menu and focus on the red settings.
    Ignored any command line options.
    Can not open config-file. Please check if file is present and you entered filename and path correctly.
    Please go to settings-menu and enter the correct configuration-settings.

**Comment by CutePoisonX** [comment]
Hi! Since you already created the necessary directories, it should work. 
This message is printed out when some settings are invalid (this does not mean that PoisonConvert could not find the settings-file). So change the invalid settings in the settings menu and the message should disappear.
